



export const FETCH_SERVICES = 'FETCH_SERVICES'
export const SERVICE_DETAILS = 'SERVICE_DETAILS'
export const IS_FEATCHING = 'IS_FEATCHING'
export const SET_AUTH_USER = 'SET_AUTH_USER'
export const RESET_AUTH_STATE = 'RESET_AUTH_STATE'
export const FETCH_USER_SERVICES = 'FETCH_USER_SERVICES'
export const FETCH_OFFERS_SUCCESS = 'FETCH_OFFERS_SUCCESS'
export const UPDATE_OFFER_STATUS_SUCCESS = 'UPDATE_OFFER_STATUS_SUCCESS'
export const COLLABORATION_CREATED_FROM_OFFER = 'COLLABORATION_CREATED_FROM_OFFER'
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS'